spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectdb
    username: root
    password: root
  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: fabian81tester@gmail.com
    password: JoyDivision80&
    properties: 
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
server:
  context-path: /locationweb


    
